// autogenerated file
#include "Behaviour.hpp"

#define GP_CREATE_INSTANCE(CLASS_NAME, INTERFACE) \
extern "C" INTERFACE* create ## CLASS_NAME () \
{ \
     return new CLASS_NAME; \
}

GP_CREATE_INSTANCE(Behaviour, IBehaviour)