theme mainMenu
{
    texture = res/common/theme.png

    imageList normalImages
    {
        color = #4A8799ff

        image unchecked
        {
            region = 78, 1, 46, 46
        }

        image checked
        {
            region = 78, 46, 46, 46
        }

        image unselected
        {
            region = 127, 1, 46, 46
        }

        image selected
        {
            region = 127, 46, 46, 46
        }

        image minCap
        {
            region = 3, 99, 8, 24
        }

        image maxCap
        {
            region = 3, 99, 8, 24
        }

        image marker
        {
            region = 16, 113, 18, 18
        }

        image track
        {
            region = 39, 119, 32, 6
        }

        image textCaret
        {
            region = 5, 149, 11, 25
            color = #C3D9BFff
        }

        image scrollBarTopCap
        {
            region = 0, 99, 12, 5
        }

        image verticalScrollBar
        {
            region = 0, 104, 12, 19
        }

        image scrollBarBottomCap
        {
            region = 0, 138, 12, 5
        }
    }

    imageList activeImages : normalImages
    {
        color = #C3D9BFff

        image unchecked
        {
            region = 78, 91, 46, 46
        }

        image checked
        {
            region = 78, 91, 46, 46
        }

        image unselected
        {
            region = 127, 91, 46, 46
        }

        image selected
        {
            region = 127, 91, 46, 46
        }
    }

    skin mainNormal
    {
        border
        {
            left = 10
            right = 10
            top = 10
            bottom = 10
        }
        
        region = 1, 1, 74, 74
        color = #4A8799ff
    }

    skin mainActive : mainNormal
    {
        color = #C3D9BFff
    }

    style basic
    {
        stateNormal
        {
            skin = mainNormal
            imageList = normalImages

            font = res/common/arial18.gpb
            textColor = #ffffffff
            fontSize = 18
            textAlignment = ALIGN_VCENTER_HCENTER
        }

        stateActive
        {
            imageList = activeImages
        }
    }

    style buttonStyle : basic
    {
        padding
        {
            top = -10
            bottom = -10
        }

        stateNormal
        {
            font = res/common/arial18.gpb
            fontSize = 20
        }

        stateActive
        {
            skin = mainActive
        }
    }

    style noBorder
    {
        stateNormal
        {
            imageList = normalImages
            font = res/common/arial18.gpb
            textColor = #ffffffff
            fontSize = 14
            textAlignment = ALIGN_VCENTER_HCENTER
        }

        stateActive
        {
            imageList = activeImages
            textAlignment = ALIGN_VCENTER_HCENTER
        }
    }

    style iconNoBorder : noBorder
    {
        stateNormal
        {
            font = res/common/arial18.gpb
            fontSize = 20
            textAlignment = ALIGN_VCENTER_LEFT
        }

        stateActive
        {
            font = res/common/arial18.gpb
            fontSize = 20
            textAlignment = ALIGN_VCENTER_LEFT
        }
    }

    style title
    {
        stateNormal
        {
            textColor = #ffffffff
            font = res/common/arial18.gpb
            fontSize = 26
            textAlignment = ALIGN_BOTTOM_HCENTER
        }

        stateActive
        {
            textColor = #C3D9BFff
        }
    }
}