// Autogenerated by gameplay-luagen
#ifndef LUA_PHYSICSCOLLISIONOBJECTCOLLISIONPAIR_H_
#define LUA_PHYSICSCOLLISIONOBJECTCOLLISIONPAIR_H_

namespace gameplay
{

void luaRegister_PhysicsCollisionObjectCollisionPair();

}

#endif
