// Autogenerated by gameplay-luagen
#ifndef LUA_PHYSICSRIGIDBODYPARAMETERS_H_
#define LUA_PHYSICSRIGIDBODYPARAMETERS_H_

namespace gameplay
{

void luaRegister_PhysicsRigidBodyParameters();

}

#endif
