// Autogenerated by gameplay-luagen
#ifndef LUA_PHYSICSCOLLISIONSHAPEDEFINITION_H_
#define LUA_PHYSICSCOLLISIONSHAPEDEFINITION_H_

namespace gameplay
{

void luaRegister_PhysicsCollisionShapeDefinition();

}

#endif
