// Autogenerated by gameplay-luagen
#ifndef LUA_PHYSICSCONTROLLERHITRESULT_H_
#define LUA_PHYSICSCONTROLLERHITRESULT_H_

namespace gameplay
{

void luaRegister_PhysicsControllerHitResult();

}

#endif
