// Autogenerated by gameplay-luagen
#ifndef LUA_SCRIPTTARGETEVENT_H_
#define LUA_SCRIPTTARGETEVENT_H_

namespace gameplay
{

// Lua bindings for ScriptTarget::Event.
int lua_ScriptTargetEvent__gc(lua_State* state);
int lua_ScriptTargetEvent__init(lua_State* state);
int lua_ScriptTargetEvent_getArgs(lua_State* state);
int lua_ScriptTargetEvent_getName(lua_State* state);

void luaRegister_ScriptTargetEvent();

}

#endif
